/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DevFloorPlanRouteImport } from './routes/dev/floor-plan'
import { Route as ScenariosScenarioIdRouteRouteImport } from './routes/scenarios/$scenarioId/route'
import { Route as SessionsSessionIdRouteRouteImport } from './routes/sessions/$sessionId/route'
import { Route as ScenariosScenarioIdIndexRouteImport } from './routes/scenarios/$scenarioId/index'
import { Route as ScenariosScenarioIdBriefingRouteImport } from './routes/scenarios/$scenarioId/briefing'
import { Route as ScenariosScenarioIdDetectiveRouteImport } from './routes/scenarios/$scenarioId/detective'
import { Route as ScenariosScenarioIdOverviewRouteImport } from './routes/scenarios/$scenarioId/overview'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions/$sessionId/index'
import { Route as SessionsSessionIdAccuseRouteImport } from './routes/sessions/$sessionId/accuse'
import { Route as SessionsSessionIdResultRouteImport } from './routes/sessions/$sessionId/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFloorPlanRoute = DevFloorPlanRouteImport.update({
  id: '/dev/floor-plan',
  path: '/dev/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdRouteRoute =
  ScenariosScenarioIdRouteRouteImport.update({
    id: '/scenarios/$scenarioId',
    path: '/scenarios/$scenarioId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SessionsSessionIdRouteRoute = SessionsSessionIdRouteRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdIndexRoute =
  ScenariosScenarioIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ScenariosScenarioIdRouteRoute,
  } as any)
const ScenariosScenarioIdBriefingRoute =
  ScenariosScenarioIdBriefingRouteImport.update({
    id: '/briefing',
    path: '/briefing',
    getParentRoute: () => ScenariosScenarioIdRouteRoute,
  } as any)
const ScenariosScenarioIdDetectiveRoute =
  ScenariosScenarioIdDetectiveRouteImport.update({
    id: '/detective',
    path: '/detective',
    getParentRoute: () => ScenariosScenarioIdRouteRoute,
  } as any)
const ScenariosScenarioIdOverviewRoute =
  ScenariosScenarioIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ScenariosScenarioIdRouteRoute,
  } as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)
const SessionsSessionIdAccuseRoute = SessionsSessionIdAccuseRouteImport.update({
  id: '/accuse',
  path: '/accuse',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)
const SessionsSessionIdResultRoute = SessionsSessionIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => SessionsSessionIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRouteRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRouteRouteWithChildren
  '/dev/floor-plan': typeof DevFloorPlanRoute
  '/scenarios/$scenarioId/briefing': typeof ScenariosScenarioIdBriefingRoute
  '/scenarios/$scenarioId/detective': typeof ScenariosScenarioIdDetectiveRoute
  '/scenarios/$scenarioId/overview': typeof ScenariosScenarioIdOverviewRoute
  '/sessions/$sessionId/accuse': typeof SessionsSessionIdAccuseRoute
  '/sessions/$sessionId/result': typeof SessionsSessionIdResultRoute
  '/scenarios/$scenarioId/': typeof ScenariosScenarioIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/floor-plan': typeof DevFloorPlanRoute
  '/scenarios/$scenarioId/briefing': typeof ScenariosScenarioIdBriefingRoute
  '/scenarios/$scenarioId/detective': typeof ScenariosScenarioIdDetectiveRoute
  '/scenarios/$scenarioId/overview': typeof ScenariosScenarioIdOverviewRoute
  '/sessions/$sessionId/accuse': typeof SessionsSessionIdAccuseRoute
  '/sessions/$sessionId/result': typeof SessionsSessionIdResultRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdIndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRouteRouteWithChildren
  '/sessions/$sessionId': typeof SessionsSessionIdRouteRouteWithChildren
  '/dev/floor-plan': typeof DevFloorPlanRoute
  '/scenarios/$scenarioId/briefing': typeof ScenariosScenarioIdBriefingRoute
  '/scenarios/$scenarioId/detective': typeof ScenariosScenarioIdDetectiveRoute
  '/scenarios/$scenarioId/overview': typeof ScenariosScenarioIdOverviewRoute
  '/sessions/$sessionId/accuse': typeof SessionsSessionIdAccuseRoute
  '/sessions/$sessionId/result': typeof SessionsSessionIdResultRoute
  '/scenarios/$scenarioId/': typeof ScenariosScenarioIdIndexRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/scenarios/$scenarioId'
    | '/sessions/$sessionId'
    | '/dev/floor-plan'
    | '/scenarios/$scenarioId/briefing'
    | '/scenarios/$scenarioId/detective'
    | '/scenarios/$scenarioId/overview'
    | '/sessions/$sessionId/accuse'
    | '/sessions/$sessionId/result'
    | '/scenarios/$scenarioId/'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dev/floor-plan'
    | '/scenarios/$scenarioId/briefing'
    | '/scenarios/$scenarioId/detective'
    | '/scenarios/$scenarioId/overview'
    | '/sessions/$sessionId/accuse'
    | '/sessions/$sessionId/result'
    | '/scenarios/$scenarioId'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/scenarios/$scenarioId'
    | '/sessions/$sessionId'
    | '/dev/floor-plan'
    | '/scenarios/$scenarioId/briefing'
    | '/scenarios/$scenarioId/detective'
    | '/scenarios/$scenarioId/overview'
    | '/sessions/$sessionId/accuse'
    | '/sessions/$sessionId/result'
    | '/scenarios/$scenarioId/'
    | '/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ScenariosScenarioIdRouteRoute: typeof ScenariosScenarioIdRouteRouteWithChildren
  SessionsSessionIdRouteRoute: typeof SessionsSessionIdRouteRouteWithChildren
  DevFloorPlanRoute: typeof DevFloorPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/floor-plan': {
      id: '/dev/floor-plan'
      path: '/dev/floor-plan'
      fullPath: '/dev/floor-plan'
      preLoaderRoute: typeof DevFloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId': {
      id: '/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ScenariosScenarioIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId/': {
      id: '/scenarios/$scenarioId/'
      path: '/'
      fullPath: '/scenarios/$scenarioId/'
      preLoaderRoute: typeof ScenariosScenarioIdIndexRouteImport
      parentRoute: typeof ScenariosScenarioIdRouteRoute
    }
    '/scenarios/$scenarioId/briefing': {
      id: '/scenarios/$scenarioId/briefing'
      path: '/briefing'
      fullPath: '/scenarios/$scenarioId/briefing'
      preLoaderRoute: typeof ScenariosScenarioIdBriefingRouteImport
      parentRoute: typeof ScenariosScenarioIdRouteRoute
    }
    '/scenarios/$scenarioId/detective': {
      id: '/scenarios/$scenarioId/detective'
      path: '/detective'
      fullPath: '/scenarios/$scenarioId/detective'
      preLoaderRoute: typeof ScenariosScenarioIdDetectiveRouteImport
      parentRoute: typeof ScenariosScenarioIdRouteRoute
    }
    '/scenarios/$scenarioId/overview': {
      id: '/scenarios/$scenarioId/overview'
      path: '/overview'
      fullPath: '/scenarios/$scenarioId/overview'
      preLoaderRoute: typeof ScenariosScenarioIdOverviewRouteImport
      parentRoute: typeof ScenariosScenarioIdRouteRoute
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/accuse': {
      id: '/sessions/$sessionId/accuse'
      path: '/accuse'
      fullPath: '/sessions/$sessionId/accuse'
      preLoaderRoute: typeof SessionsSessionIdAccuseRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
    '/sessions/$sessionId/result': {
      id: '/sessions/$sessionId/result'
      path: '/result'
      fullPath: '/sessions/$sessionId/result'
      preLoaderRoute: typeof SessionsSessionIdResultRouteImport
      parentRoute: typeof SessionsSessionIdRouteRoute
    }
  }
}

interface ScenariosScenarioIdRouteRouteChildren {
  ScenariosScenarioIdBriefingRoute: typeof ScenariosScenarioIdBriefingRoute
  ScenariosScenarioIdDetectiveRoute: typeof ScenariosScenarioIdDetectiveRoute
  ScenariosScenarioIdOverviewRoute: typeof ScenariosScenarioIdOverviewRoute
  ScenariosScenarioIdIndexRoute: typeof ScenariosScenarioIdIndexRoute
}

const ScenariosScenarioIdRouteRouteChildren: ScenariosScenarioIdRouteRouteChildren =
  {
    ScenariosScenarioIdBriefingRoute: ScenariosScenarioIdBriefingRoute,
    ScenariosScenarioIdDetectiveRoute: ScenariosScenarioIdDetectiveRoute,
    ScenariosScenarioIdOverviewRoute: ScenariosScenarioIdOverviewRoute,
    ScenariosScenarioIdIndexRoute: ScenariosScenarioIdIndexRoute,
  }

const ScenariosScenarioIdRouteRouteWithChildren =
  ScenariosScenarioIdRouteRoute._addFileChildren(
    ScenariosScenarioIdRouteRouteChildren,
  )

interface SessionsSessionIdRouteRouteChildren {
  SessionsSessionIdAccuseRoute: typeof SessionsSessionIdAccuseRoute
  SessionsSessionIdResultRoute: typeof SessionsSessionIdResultRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

const SessionsSessionIdRouteRouteChildren: SessionsSessionIdRouteRouteChildren =
  {
    SessionsSessionIdAccuseRoute: SessionsSessionIdAccuseRoute,
    SessionsSessionIdResultRoute: SessionsSessionIdResultRoute,
    SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
  }

const SessionsSessionIdRouteRouteWithChildren =
  SessionsSessionIdRouteRoute._addFileChildren(
    SessionsSessionIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ScenariosScenarioIdRouteRoute: ScenariosScenarioIdRouteRouteWithChildren,
  SessionsSessionIdRouteRoute: SessionsSessionIdRouteRouteWithChildren,
  DevFloorPlanRoute: DevFloorPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
